name: Lint

on: [push, pull_request]

jobs:
    php-cs-fixer:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 7.4
                    coverage: none
                    tools: php-cs-fixer:2.19.3

            -   name: Run PHP-CS-Fixer
                run: php-cs-fixer fix --dry-run --diff

            -   name: Run composer normalize
                run: |
                    composer require --dev ergebnis/composer-normalize
                    composer config allow-plugins.ergebnis/composer-normalize true
                    composer normalize --dry-run
