name: Static analysis

on: [push, pull_request]

jobs:
    static-analysis:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 7.4
                    coverage: none
                    tools: php-cs-fixer:^3.14

            -   name: Run PHP-CS-Fixer
                run: php-cs-fixer fix --dry-run

            -   name: Run composer normalize
                run: |
                    composer global config allow-plugins.ergebnis/composer-normalize true
                    composer global require ergebnis/composer-normalize
                    composer normalize --dry-run
