name: Tests

on: [push, pull_request]

jobs:
    tests:
        name: "PHP${{ matrix.php }} Symfony${{ matrix.symfony}} ${{ matrix.composer-flags }}"
        runs-on: ubuntu-latest

        strategy:
            fail-fast: false
            matrix:
                include:
                    -   php: '7.1'
                        symfony: '^3.4'
                        coverage: 'xdebug'
                        composer-flags: '--prefer-lowest'
                    -   php: '7.2'
                        symfony: '^4.0'
                    -   php: '7.3'
                        symfony: '^5.0'
                    -   php: '7.4'
                        symfony: '^5.0'
                    -   php: '8.0'
                        symfony: '^5.0'
                    -   php: '8.1'
                        symfony: '^5.0'
                    -   php: '8.2'
                        symfony: '^5.0'
                        coverage: 'pcov'
        steps:
            -   name: Checkout source
                uses: actions/checkout@v2

            -   name: PHP setup
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    coverage: ${{ matrix.coverage || 'none' }}

            -   name: Install Symfony Flex
                run: |
                    composer global config allow-plugins.symfony/flex true
                    composer global require -o --no-interaction --no-progress symfony/flex:"^1.11 || ^2.0"

            -   name: Require Symfony version
                run: composer config extra.symfony.require ${{ matrix.symfony }}

            -   name: Update composer dependencies
                run: composer update -o --no-interaction --no-progress ${{ matrix.composer-flags }}

            -   name: Run test suite
                run: ./vendor/bin/simple-phpunit -v --coverage-clover var/build/clover.xml

            -   name: Install php-coveralls
                run: composer global require -o --no-interaction --no-progress php-coveralls/php-coveralls

            -   name: Upload coverage results to Coveralls
                if: matrix.coverage
                uses: nick-invision/retry@v2
                env:
                    COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                    COVERALLS_PARALLEL: true
                    COVERALLS_FLAG_NAME: "PHP${{ matrix.php }} Symfony${{ matrix.symfony}}"
                with:
                    timeout_seconds: 60
                    max_attempts: 3
                    command: php-coveralls -x var/build/clover.xml -o var/build/upload.json -v

    coveralls-finish:
        needs: tests
        runs-on: ubuntu-latest
        steps:
            -   name: Notify Coveralls when build is finished
                uses: coverallsapp/github-action@master
                with:
                    github-token: ${{ secrets.GITHUB_TOKEN }}
                    parallel-finished: true
